// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	activity2 "big-market-kratos/internal/biz/activity"
	award2 "big-market-kratos/internal/biz/award"
	rebate2 "big-market-kratos/internal/biz/rebate"
	strategy2 "big-market-kratos/internal/biz/strategy"
	task2 "big-market-kratos/internal/biz/task"
	"big-market-kratos/internal/conf"
	"big-market-kratos/internal/data"
	"big-market-kratos/internal/data/activity"
	"big-market-kratos/internal/data/award"
	"big-market-kratos/internal/data/infra"
	"big-market-kratos/internal/data/rebate"
	"big-market-kratos/internal/data/strategy"
	"big-market-kratos/internal/data/task"
	"big-market-kratos/internal/dcc"
	"big-market-kratos/internal/job"
	"big-market-kratos/internal/listener"
	"big-market-kratos/internal/server"
	"big-market-kratos/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
	_ "net/http/pprof"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, rabbitMQ *conf.RabbitMQ, asynq *conf.Asynq, monitor *conf.Monitor, logger log.Logger, configGetter dcc.ConfigGetter) (*kratos.App, func(), error) {
	data_Mysql := data.NewMysqlConfig(confData)
	db := infra.NewDB(data_Mysql)
	data_Redis := data.NewRedisConfig(confData)
	cache := infra.NewRedisClient(data_Redis)
	client := infra.NewAsynqClient(asynq)
	dbRouter := infra.NewDBRouter(data_Mysql)
	repo := strategy.NewStrategyRepository(db, cache, client, dbRouter)
	strategyUsecase := strategy2.NewStrategyUsecase(repo)
	connection, err := infra.NewConnection(rabbitMQ)
	if err != nil {
		return nil, nil, err
	}
	rabbitMQPublisher, err := infra.NewRabbitMQPublisher(connection)
	if err != nil {
		return nil, nil, err
	}
	publisher := infra.NewPublisher(rabbitMQPublisher, rabbitMQ)
	inspector := infra.NewAsynqInspector(asynq)
	activityRepo := activity.NewRepository(dbRouter, db, cache, publisher, client, inspector)
	activityQuotaUsecase := activity2.NewActivityQuotaUsecase(activityRepo)
	strategyService := service.NewStrategyService(strategyUsecase, activityQuotaUsecase)
	stockManager := activity2.NewStockManager(activityRepo)
	activityPartakeUsecase := activity2.NewActivityPartakeUsecase(activityRepo)
	awardRepo := award.NewUserAwardRecordRepository(dbRouter, cache, publisher)
	awardUsecase := award2.NewAwardUsecase(awardRepo)
	rebateRepo := rebate.NewRebateRepository(db, dbRouter, publisher)
	behaviorRebateUsecase := rebate2.NewBehaviorRebateUsecase(rebateRepo)
	activityService := service.NewActivityService(stockManager, activityPartakeUsecase, activityQuotaUsecase, strategyUsecase, awardUsecase, behaviorRebateUsecase)
	grpcServer := server.NewGRPCServer(confServer, strategyService, activityService, logger)
	httpServer := server.NewHTTPServer(confServer, strategyService, activityService, logger, configGetter)
	metricsServer := server.NewMetricsServer(monitor, logger)
	activitySkuStockConsumeJob := job.NewActivitySkuStockConsumeJob(activityQuotaUsecase)
	taskRepo := task.NewTaskRepository(dbRouter, publisher)
	taskUsecase := task2.NewTaskUsecase(taskRepo)
	sendAwardMessage := job.NewSendAwardMessage(taskUsecase, activityPartakeUsecase, data_Mysql)
	strategyAwardStockConsumeJob := job.NewStrategyAwardStockConsumeJob(strategyUsecase)
	asynqServer := server.NewAsynqServer(asynq, activitySkuStockConsumeJob, sendAwardMessage, strategyAwardStockConsumeJob)
	activityStockListener := listener.NewActivityStockListener(activityQuotaUsecase)
	rebateListener := listener.NewRebateListener(activityQuotaUsecase)
	saveOrderListener := listener.NewSaveOrderListener(activityPartakeUsecase)
	rabbitMQServer := server.NewRabbitMQServer(connection, activityStockListener, rebateListener, saveOrderListener)
	app := newApp(logger, grpcServer, httpServer, metricsServer, asynqServer, rabbitMQServer)
	return app, func() {
	}, nil
}
