// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: bigmarket/v1/activity.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaffleActivityArmoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaffleActivityArmoryRequest) Reset() {
	*x = RaffleActivityArmoryRequest{}
	mi := &file_bigmarket_v1_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaffleActivityArmoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaffleActivityArmoryRequest) ProtoMessage() {}

func (x *RaffleActivityArmoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaffleActivityArmoryRequest.ProtoReflect.Descriptor instead.
func (*RaffleActivityArmoryRequest) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_activity_proto_rawDescGZIP(), []int{0}
}

func (x *RaffleActivityArmoryRequest) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type RaffleActivityArmoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaffleActivityArmoryReply) Reset() {
	*x = RaffleActivityArmoryReply{}
	mi := &file_bigmarket_v1_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaffleActivityArmoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaffleActivityArmoryReply) ProtoMessage() {}

func (x *RaffleActivityArmoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaffleActivityArmoryReply.ProtoReflect.Descriptor instead.
func (*RaffleActivityArmoryReply) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_activity_proto_rawDescGZIP(), []int{1}
}

func (x *RaffleActivityArmoryReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawRequest) Reset() {
	*x = DrawRequest{}
	mi := &file_bigmarket_v1_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawRequest) ProtoMessage() {}

func (x *DrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawRequest.ProtoReflect.Descriptor instead.
func (*DrawRequest) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_activity_proto_rawDescGZIP(), []int{2}
}

func (x *DrawRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DrawRequest) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type DrawReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AwardId       int64                  `protobuf:"varint,1,opt,name=award_id,json=awardId,proto3" json:"award_id,omitempty"`
	AwardTitle    string                 `protobuf:"bytes,2,opt,name=award_title,json=awardTitle,proto3" json:"award_title,omitempty"`
	AwardIndex    int32                  `protobuf:"varint,3,opt,name=award_index,json=awardIndex,proto3" json:"award_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawReply) Reset() {
	*x = DrawReply{}
	mi := &file_bigmarket_v1_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawReply) ProtoMessage() {}

func (x *DrawReply) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawReply.ProtoReflect.Descriptor instead.
func (*DrawReply) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_activity_proto_rawDescGZIP(), []int{3}
}

func (x *DrawReply) GetAwardId() int64 {
	if x != nil {
		return x.AwardId
	}
	return 0
}

func (x *DrawReply) GetAwardTitle() string {
	if x != nil {
		return x.AwardTitle
	}
	return ""
}

func (x *DrawReply) GetAwardIndex() int32 {
	if x != nil {
		return x.AwardIndex
	}
	return 0
}

type CalendarSignRebateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarSignRebateRequest) Reset() {
	*x = CalendarSignRebateRequest{}
	mi := &file_bigmarket_v1_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarSignRebateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarSignRebateRequest) ProtoMessage() {}

func (x *CalendarSignRebateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarSignRebateRequest.ProtoReflect.Descriptor instead.
func (*CalendarSignRebateRequest) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_activity_proto_rawDescGZIP(), []int{4}
}

func (x *CalendarSignRebateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CalendarSignRebateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarSignRebateReply) Reset() {
	*x = CalendarSignRebateReply{}
	mi := &file_bigmarket_v1_activity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarSignRebateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarSignRebateReply) ProtoMessage() {}

func (x *CalendarSignRebateReply) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_activity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarSignRebateReply.ProtoReflect.Descriptor instead.
func (*CalendarSignRebateReply) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_activity_proto_rawDescGZIP(), []int{5}
}

func (x *CalendarSignRebateReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IsCalendarSignRebateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsCalendarSignRebateRequest) Reset() {
	*x = IsCalendarSignRebateRequest{}
	mi := &file_bigmarket_v1_activity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCalendarSignRebateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCalendarSignRebateRequest) ProtoMessage() {}

func (x *IsCalendarSignRebateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_activity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCalendarSignRebateRequest.ProtoReflect.Descriptor instead.
func (*IsCalendarSignRebateRequest) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_activity_proto_rawDescGZIP(), []int{6}
}

func (x *IsCalendarSignRebateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsCalendarSignRebateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSigned      bool                   `protobuf:"varint,1,opt,name=is_signed,json=isSigned,proto3" json:"is_signed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsCalendarSignRebateReply) Reset() {
	*x = IsCalendarSignRebateReply{}
	mi := &file_bigmarket_v1_activity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCalendarSignRebateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCalendarSignRebateReply) ProtoMessage() {}

func (x *IsCalendarSignRebateReply) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_activity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCalendarSignRebateReply.ProtoReflect.Descriptor instead.
func (*IsCalendarSignRebateReply) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_activity_proto_rawDescGZIP(), []int{7}
}

func (x *IsCalendarSignRebateReply) GetIsSigned() bool {
	if x != nil {
		return x.IsSigned
	}
	return false
}

type QueryUserActivityAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUserActivityAccountRequest) Reset() {
	*x = QueryUserActivityAccountRequest{}
	mi := &file_bigmarket_v1_activity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserActivityAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserActivityAccountRequest) ProtoMessage() {}

func (x *QueryUserActivityAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_activity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserActivityAccountRequest.ProtoReflect.Descriptor instead.
func (*QueryUserActivityAccountRequest) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_activity_proto_rawDescGZIP(), []int{8}
}

func (x *QueryUserActivityAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryUserActivityAccountRequest) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type QueryUserActivityAccountReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActivityId        int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	TotalCount        int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalCountSurplus int64                  `protobuf:"varint,3,opt,name=total_count_surplus,json=totalCountSurplus,proto3" json:"total_count_surplus,omitempty"`
	DayCount          int64                  `protobuf:"varint,4,opt,name=day_count,json=dayCount,proto3" json:"day_count,omitempty"`
	DayCountSurplus   int64                  `protobuf:"varint,5,opt,name=day_count_surplus,json=dayCountSurplus,proto3" json:"day_count_surplus,omitempty"`
	MonthCount        int64                  `protobuf:"varint,6,opt,name=month_count,json=monthCount,proto3" json:"month_count,omitempty"`
	MonthCountSurplus int64                  `protobuf:"varint,7,opt,name=month_count_surplus,json=monthCountSurplus,proto3" json:"month_count_surplus,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryUserActivityAccountReply) Reset() {
	*x = QueryUserActivityAccountReply{}
	mi := &file_bigmarket_v1_activity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserActivityAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserActivityAccountReply) ProtoMessage() {}

func (x *QueryUserActivityAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_activity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserActivityAccountReply.ProtoReflect.Descriptor instead.
func (*QueryUserActivityAccountReply) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_activity_proto_rawDescGZIP(), []int{9}
}

func (x *QueryUserActivityAccountReply) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *QueryUserActivityAccountReply) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *QueryUserActivityAccountReply) GetTotalCountSurplus() int64 {
	if x != nil {
		return x.TotalCountSurplus
	}
	return 0
}

func (x *QueryUserActivityAccountReply) GetDayCount() int64 {
	if x != nil {
		return x.DayCount
	}
	return 0
}

func (x *QueryUserActivityAccountReply) GetDayCountSurplus() int64 {
	if x != nil {
		return x.DayCountSurplus
	}
	return 0
}

func (x *QueryUserActivityAccountReply) GetMonthCount() int64 {
	if x != nil {
		return x.MonthCount
	}
	return 0
}

func (x *QueryUserActivityAccountReply) GetMonthCountSurplus() int64 {
	if x != nil {
		return x.MonthCountSurplus
	}
	return 0
}

var File_bigmarket_v1_activity_proto protoreflect.FileDescriptor

const file_bigmarket_v1_activity_proto_rawDesc = "" +
	"\n" +
	"\x1bbigmarket/v1/activity.proto\x12\x10api.bigmarket.v1\x1a\x1cgoogle/api/annotations.proto\">\n" +
	"\x1bRaffleActivityArmoryRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\"5\n" +
	"\x19RaffleActivityArmoryReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"G\n" +
	"\vDrawRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\"h\n" +
	"\tDrawReply\x12\x19\n" +
	"\baward_id\x18\x01 \x01(\x03R\aawardId\x12\x1f\n" +
	"\vaward_title\x18\x02 \x01(\tR\n" +
	"awardTitle\x12\x1f\n" +
	"\vaward_index\x18\x03 \x01(\x05R\n" +
	"awardIndex\"4\n" +
	"\x19CalendarSignRebateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"3\n" +
	"\x17CalendarSignRebateReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"6\n" +
	"\x1bIsCalendarSignRebateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x19IsCalendarSignRebateReply\x12\x1b\n" +
	"\tis_signed\x18\x01 \x01(\bR\bisSigned\"[\n" +
	"\x1fQueryUserActivityAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\"\xab\x02\n" +
	"\x1dQueryUserActivityAccountReply\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12.\n" +
	"\x13total_count_surplus\x18\x03 \x01(\x03R\x11totalCountSurplus\x12\x1b\n" +
	"\tday_count\x18\x04 \x01(\x03R\bdayCount\x12*\n" +
	"\x11day_count_surplus\x18\x05 \x01(\x03R\x0fdayCountSurplus\x12\x1f\n" +
	"\vmonth_count\x18\x06 \x01(\x03R\n" +
	"monthCount\x12.\n" +
	"\x13month_count_surplus\x18\a \x01(\x03R\x11monthCountSurplus2\xdb\x06\n" +
	"\bActivity\x12\xa3\x01\n" +
	"\x14RaffleActivityArmory\x12-.api.bigmarket.v1.RaffleActivityArmoryRequest\x1a+.api.bigmarket.v1.RaffleActivityArmoryReply\"/\x82\xd3\xe4\x93\x02)\x12'/api/v1/strategy/raffle/activity/armory\x12t\n" +
	"\x04Draw\x12\x1d.api.bigmarket.v1.DrawRequest\x1a\x1b.api.bigmarket.v1.DrawReply\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/v1/strategy/raffle/activity/draw\x12\xae\x01\n" +
	"\x12CalendarSignRebate\x12+.api.bigmarket.v1.CalendarSignRebateRequest\x1a).api.bigmarket.v1.CalendarSignRebateReply\"@\x82\xd3\xe4\x93\x02::\x01*\"5/api/v1/strategy/raffle/activity/calendar_sign_rebate\x12\xb7\x01\n" +
	"\x14IsCalendarSignRebate\x12-.api.bigmarket.v1.IsCalendarSignRebateRequest\x1a+.api.bigmarket.v1.IsCalendarSignRebateReply\"C\x82\xd3\xe4\x93\x02=:\x01*\"8/api/v1/strategy/raffle/activity/is_calendar_sign_rebate\x12\xc7\x01\n" +
	"\x18QueryUserActivityAccount\x121.api.bigmarket.v1.QueryUserActivityAccountRequest\x1a/.api.bigmarket.v1.QueryUserActivityAccountReply\"G\x82\xd3\xe4\x93\x02A:\x01*\"</api/v1/strategy/raffle/activity/query_user_activity_accountB;\n" +
	"\x10api.bigmarket.v1P\x01Z%big-market-kratos/api/bigmarket/v1;v1b\x06proto3"

var (
	file_bigmarket_v1_activity_proto_rawDescOnce sync.Once
	file_bigmarket_v1_activity_proto_rawDescData []byte
)

func file_bigmarket_v1_activity_proto_rawDescGZIP() []byte {
	file_bigmarket_v1_activity_proto_rawDescOnce.Do(func() {
		file_bigmarket_v1_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bigmarket_v1_activity_proto_rawDesc), len(file_bigmarket_v1_activity_proto_rawDesc)))
	})
	return file_bigmarket_v1_activity_proto_rawDescData
}

var file_bigmarket_v1_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bigmarket_v1_activity_proto_goTypes = []any{
	(*RaffleActivityArmoryRequest)(nil),     // 0: api.bigmarket.v1.RaffleActivityArmoryRequest
	(*RaffleActivityArmoryReply)(nil),       // 1: api.bigmarket.v1.RaffleActivityArmoryReply
	(*DrawRequest)(nil),                     // 2: api.bigmarket.v1.DrawRequest
	(*DrawReply)(nil),                       // 3: api.bigmarket.v1.DrawReply
	(*CalendarSignRebateRequest)(nil),       // 4: api.bigmarket.v1.CalendarSignRebateRequest
	(*CalendarSignRebateReply)(nil),         // 5: api.bigmarket.v1.CalendarSignRebateReply
	(*IsCalendarSignRebateRequest)(nil),     // 6: api.bigmarket.v1.IsCalendarSignRebateRequest
	(*IsCalendarSignRebateReply)(nil),       // 7: api.bigmarket.v1.IsCalendarSignRebateReply
	(*QueryUserActivityAccountRequest)(nil), // 8: api.bigmarket.v1.QueryUserActivityAccountRequest
	(*QueryUserActivityAccountReply)(nil),   // 9: api.bigmarket.v1.QueryUserActivityAccountReply
}
var file_bigmarket_v1_activity_proto_depIdxs = []int32{
	0, // 0: api.bigmarket.v1.Activity.RaffleActivityArmory:input_type -> api.bigmarket.v1.RaffleActivityArmoryRequest
	2, // 1: api.bigmarket.v1.Activity.Draw:input_type -> api.bigmarket.v1.DrawRequest
	4, // 2: api.bigmarket.v1.Activity.CalendarSignRebate:input_type -> api.bigmarket.v1.CalendarSignRebateRequest
	6, // 3: api.bigmarket.v1.Activity.IsCalendarSignRebate:input_type -> api.bigmarket.v1.IsCalendarSignRebateRequest
	8, // 4: api.bigmarket.v1.Activity.QueryUserActivityAccount:input_type -> api.bigmarket.v1.QueryUserActivityAccountRequest
	1, // 5: api.bigmarket.v1.Activity.RaffleActivityArmory:output_type -> api.bigmarket.v1.RaffleActivityArmoryReply
	3, // 6: api.bigmarket.v1.Activity.Draw:output_type -> api.bigmarket.v1.DrawReply
	5, // 7: api.bigmarket.v1.Activity.CalendarSignRebate:output_type -> api.bigmarket.v1.CalendarSignRebateReply
	7, // 8: api.bigmarket.v1.Activity.IsCalendarSignRebate:output_type -> api.bigmarket.v1.IsCalendarSignRebateReply
	9, // 9: api.bigmarket.v1.Activity.QueryUserActivityAccount:output_type -> api.bigmarket.v1.QueryUserActivityAccountReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bigmarket_v1_activity_proto_init() }
func file_bigmarket_v1_activity_proto_init() {
	if File_bigmarket_v1_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bigmarket_v1_activity_proto_rawDesc), len(file_bigmarket_v1_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bigmarket_v1_activity_proto_goTypes,
		DependencyIndexes: file_bigmarket_v1_activity_proto_depIdxs,
		MessageInfos:      file_bigmarket_v1_activity_proto_msgTypes,
	}.Build()
	File_bigmarket_v1_activity_proto = out.File
	file_bigmarket_v1_activity_proto_goTypes = nil
	file_bigmarket_v1_activity_proto_depIdxs = nil
}
