// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.4
// source: bigmarket/v1/activity.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationActivityCalendarSignRebate = "/api.bigmarket.v1.Activity/CalendarSignRebate"
const OperationActivityDraw = "/api.bigmarket.v1.Activity/Draw"
const OperationActivityIsCalendarSignRebate = "/api.bigmarket.v1.Activity/IsCalendarSignRebate"
const OperationActivityLoadUserActivityAccount = "/api.bigmarket.v1.Activity/LoadUserActivityAccount"
const OperationActivityQueryUserActivityAccount = "/api.bigmarket.v1.Activity/QueryUserActivityAccount"
const OperationActivityRaffleActivityArmory = "/api.bigmarket.v1.Activity/RaffleActivityArmory"

type ActivityHTTPServer interface {
	// CalendarSignRebate 签到返利
	// 对应: POST /api/v1/raffle/activity/calendar_sign_rebate
	CalendarSignRebate(context.Context, *CalendarSignRebateRequest) (*CalendarSignRebateReply, error)
	// Draw 抽奖 (聚合接口)
	// 对应: POST /api/v1/raffle/activity/draw
	Draw(context.Context, *DrawRequest) (*DrawReply, error)
	// IsCalendarSignRebate 判断是否签到
	// 对应: POST /api/v1/raffle/activity/is_calendar_sign_rebate
	IsCalendarSignRebate(context.Context, *IsCalendarSignRebateRequest) (*IsCalendarSignRebateReply, error)
	// LoadUserActivityAccount 加载单个用户活动账户额度到缓存
	// 对应: POST /api/v1/raffle/activity/load_user_activity_account
	LoadUserActivityAccount(context.Context, *LoadUserActivityAccountRequest) (*LoadUserActivityAccountReply, error)
	// QueryUserActivityAccount 查询用户活动账户
	// 对应: POST /api/v1/raffle/activity/query_user_activity_account
	QueryUserActivityAccount(context.Context, *QueryUserActivityAccountRequest) (*QueryUserActivityAccountReply, error)
	// RaffleActivityArmory 活动装配
	// 对应: GET /api/v1/raffle/activity/armory?activity_id=xxx
	RaffleActivityArmory(context.Context, *RaffleActivityArmoryRequest) (*RaffleActivityArmoryReply, error)
}

func RegisterActivityHTTPServer(s *http.Server, srv ActivityHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/strategy/raffle/activity/armory", _Activity_RaffleActivityArmory0_HTTP_Handler(srv))
	r.POST("/api/v1/strategy/raffle/activity/draw", _Activity_Draw0_HTTP_Handler(srv))
	r.POST("/api/v1/strategy/raffle/activity/calendar_sign_rebate", _Activity_CalendarSignRebate0_HTTP_Handler(srv))
	r.POST("/api/v1/strategy/raffle/activity/is_calendar_sign_rebate", _Activity_IsCalendarSignRebate0_HTTP_Handler(srv))
	r.POST("/api/v1/strategy/raffle/activity/query_user_activity_account", _Activity_QueryUserActivityAccount0_HTTP_Handler(srv))
	r.POST("/api/v1/strategy/raffle/activity/load_user_activity_account", _Activity_LoadUserActivityAccount0_HTTP_Handler(srv))
}

func _Activity_RaffleActivityArmory0_HTTP_Handler(srv ActivityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RaffleActivityArmoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationActivityRaffleActivityArmory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RaffleActivityArmory(ctx, req.(*RaffleActivityArmoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RaffleActivityArmoryReply)
		return ctx.Result(200, reply)
	}
}

func _Activity_Draw0_HTTP_Handler(srv ActivityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DrawRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationActivityDraw)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Draw(ctx, req.(*DrawRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DrawReply)
		return ctx.Result(200, reply)
	}
}

func _Activity_CalendarSignRebate0_HTTP_Handler(srv ActivityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CalendarSignRebateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationActivityCalendarSignRebate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CalendarSignRebate(ctx, req.(*CalendarSignRebateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CalendarSignRebateReply)
		return ctx.Result(200, reply)
	}
}

func _Activity_IsCalendarSignRebate0_HTTP_Handler(srv ActivityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in IsCalendarSignRebateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationActivityIsCalendarSignRebate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.IsCalendarSignRebate(ctx, req.(*IsCalendarSignRebateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*IsCalendarSignRebateReply)
		return ctx.Result(200, reply)
	}
}

func _Activity_QueryUserActivityAccount0_HTTP_Handler(srv ActivityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in QueryUserActivityAccountRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationActivityQueryUserActivityAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueryUserActivityAccount(ctx, req.(*QueryUserActivityAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueryUserActivityAccountReply)
		return ctx.Result(200, reply)
	}
}

func _Activity_LoadUserActivityAccount0_HTTP_Handler(srv ActivityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoadUserActivityAccountRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationActivityLoadUserActivityAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoadUserActivityAccount(ctx, req.(*LoadUserActivityAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoadUserActivityAccountReply)
		return ctx.Result(200, reply)
	}
}

type ActivityHTTPClient interface {
	// CalendarSignRebate 签到返利
	// 对应: POST /api/v1/raffle/activity/calendar_sign_rebate
	CalendarSignRebate(ctx context.Context, req *CalendarSignRebateRequest, opts ...http.CallOption) (rsp *CalendarSignRebateReply, err error)
	// Draw 抽奖 (聚合接口)
	// 对应: POST /api/v1/raffle/activity/draw
	Draw(ctx context.Context, req *DrawRequest, opts ...http.CallOption) (rsp *DrawReply, err error)
	// IsCalendarSignRebate 判断是否签到
	// 对应: POST /api/v1/raffle/activity/is_calendar_sign_rebate
	IsCalendarSignRebate(ctx context.Context, req *IsCalendarSignRebateRequest, opts ...http.CallOption) (rsp *IsCalendarSignRebateReply, err error)
	// LoadUserActivityAccount 加载单个用户活动账户额度到缓存
	// 对应: POST /api/v1/raffle/activity/load_user_activity_account
	LoadUserActivityAccount(ctx context.Context, req *LoadUserActivityAccountRequest, opts ...http.CallOption) (rsp *LoadUserActivityAccountReply, err error)
	// QueryUserActivityAccount 查询用户活动账户
	// 对应: POST /api/v1/raffle/activity/query_user_activity_account
	QueryUserActivityAccount(ctx context.Context, req *QueryUserActivityAccountRequest, opts ...http.CallOption) (rsp *QueryUserActivityAccountReply, err error)
	// RaffleActivityArmory 活动装配
	// 对应: GET /api/v1/raffle/activity/armory?activity_id=xxx
	RaffleActivityArmory(ctx context.Context, req *RaffleActivityArmoryRequest, opts ...http.CallOption) (rsp *RaffleActivityArmoryReply, err error)
}

type ActivityHTTPClientImpl struct {
	cc *http.Client
}

func NewActivityHTTPClient(client *http.Client) ActivityHTTPClient {
	return &ActivityHTTPClientImpl{client}
}

// CalendarSignRebate 签到返利
// 对应: POST /api/v1/raffle/activity/calendar_sign_rebate
func (c *ActivityHTTPClientImpl) CalendarSignRebate(ctx context.Context, in *CalendarSignRebateRequest, opts ...http.CallOption) (*CalendarSignRebateReply, error) {
	var out CalendarSignRebateReply
	pattern := "/api/v1/strategy/raffle/activity/calendar_sign_rebate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationActivityCalendarSignRebate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Draw 抽奖 (聚合接口)
// 对应: POST /api/v1/raffle/activity/draw
func (c *ActivityHTTPClientImpl) Draw(ctx context.Context, in *DrawRequest, opts ...http.CallOption) (*DrawReply, error) {
	var out DrawReply
	pattern := "/api/v1/strategy/raffle/activity/draw"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationActivityDraw))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// IsCalendarSignRebate 判断是否签到
// 对应: POST /api/v1/raffle/activity/is_calendar_sign_rebate
func (c *ActivityHTTPClientImpl) IsCalendarSignRebate(ctx context.Context, in *IsCalendarSignRebateRequest, opts ...http.CallOption) (*IsCalendarSignRebateReply, error) {
	var out IsCalendarSignRebateReply
	pattern := "/api/v1/strategy/raffle/activity/is_calendar_sign_rebate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationActivityIsCalendarSignRebate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LoadUserActivityAccount 加载单个用户活动账户额度到缓存
// 对应: POST /api/v1/raffle/activity/load_user_activity_account
func (c *ActivityHTTPClientImpl) LoadUserActivityAccount(ctx context.Context, in *LoadUserActivityAccountRequest, opts ...http.CallOption) (*LoadUserActivityAccountReply, error) {
	var out LoadUserActivityAccountReply
	pattern := "/api/v1/strategy/raffle/activity/load_user_activity_account"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationActivityLoadUserActivityAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// QueryUserActivityAccount 查询用户活动账户
// 对应: POST /api/v1/raffle/activity/query_user_activity_account
func (c *ActivityHTTPClientImpl) QueryUserActivityAccount(ctx context.Context, in *QueryUserActivityAccountRequest, opts ...http.CallOption) (*QueryUserActivityAccountReply, error) {
	var out QueryUserActivityAccountReply
	pattern := "/api/v1/strategy/raffle/activity/query_user_activity_account"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationActivityQueryUserActivityAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RaffleActivityArmory 活动装配
// 对应: GET /api/v1/raffle/activity/armory?activity_id=xxx
func (c *ActivityHTTPClientImpl) RaffleActivityArmory(ctx context.Context, in *RaffleActivityArmoryRequest, opts ...http.CallOption) (*RaffleActivityArmoryReply, error) {
	var out RaffleActivityArmoryReply
	pattern := "/api/v1/strategy/raffle/activity/armory"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationActivityRaffleActivityArmory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
