// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: bigmarket/v1/activity.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Activity_RaffleActivityArmory_FullMethodName     = "/api.bigmarket.v1.Activity/RaffleActivityArmory"
	Activity_Draw_FullMethodName                     = "/api.bigmarket.v1.Activity/Draw"
	Activity_CalendarSignRebate_FullMethodName       = "/api.bigmarket.v1.Activity/CalendarSignRebate"
	Activity_IsCalendarSignRebate_FullMethodName     = "/api.bigmarket.v1.Activity/IsCalendarSignRebate"
	Activity_QueryUserActivityAccount_FullMethodName = "/api.bigmarket.v1.Activity/QueryUserActivityAccount"
)

// ActivityClient is the client API for Activity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityClient interface {
	// 活动装配
	// 对应: GET /api/v1/raffle/activity/armory?activity_id=xxx
	RaffleActivityArmory(ctx context.Context, in *RaffleActivityArmoryRequest, opts ...grpc.CallOption) (*RaffleActivityArmoryReply, error)
	// 抽奖 (聚合接口)
	// 对应: POST /api/v1/raffle/activity/draw
	Draw(ctx context.Context, in *DrawRequest, opts ...grpc.CallOption) (*DrawReply, error)
	// 签到返利
	// 对应: POST /api/v1/raffle/activity/calendar_sign_rebate
	CalendarSignRebate(ctx context.Context, in *CalendarSignRebateRequest, opts ...grpc.CallOption) (*CalendarSignRebateReply, error)
	// 判断是否签到
	// 对应: POST /api/v1/raffle/activity/is_calendar_sign_rebate
	IsCalendarSignRebate(ctx context.Context, in *IsCalendarSignRebateRequest, opts ...grpc.CallOption) (*IsCalendarSignRebateReply, error)
	// 查询用户活动账户
	// 对应: POST /api/v1/raffle/activity/query_user_activity_account
	QueryUserActivityAccount(ctx context.Context, in *QueryUserActivityAccountRequest, opts ...grpc.CallOption) (*QueryUserActivityAccountReply, error)
}

type activityClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityClient(cc grpc.ClientConnInterface) ActivityClient {
	return &activityClient{cc}
}

func (c *activityClient) RaffleActivityArmory(ctx context.Context, in *RaffleActivityArmoryRequest, opts ...grpc.CallOption) (*RaffleActivityArmoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RaffleActivityArmoryReply)
	err := c.cc.Invoke(ctx, Activity_RaffleActivityArmory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) Draw(ctx context.Context, in *DrawRequest, opts ...grpc.CallOption) (*DrawReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrawReply)
	err := c.cc.Invoke(ctx, Activity_Draw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) CalendarSignRebate(ctx context.Context, in *CalendarSignRebateRequest, opts ...grpc.CallOption) (*CalendarSignRebateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalendarSignRebateReply)
	err := c.cc.Invoke(ctx, Activity_CalendarSignRebate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) IsCalendarSignRebate(ctx context.Context, in *IsCalendarSignRebateRequest, opts ...grpc.CallOption) (*IsCalendarSignRebateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsCalendarSignRebateReply)
	err := c.cc.Invoke(ctx, Activity_IsCalendarSignRebate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) QueryUserActivityAccount(ctx context.Context, in *QueryUserActivityAccountRequest, opts ...grpc.CallOption) (*QueryUserActivityAccountReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserActivityAccountReply)
	err := c.cc.Invoke(ctx, Activity_QueryUserActivityAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServer is the server API for Activity service.
// All implementations must embed UnimplementedActivityServer
// for forward compatibility.
type ActivityServer interface {
	// 活动装配
	// 对应: GET /api/v1/raffle/activity/armory?activity_id=xxx
	RaffleActivityArmory(context.Context, *RaffleActivityArmoryRequest) (*RaffleActivityArmoryReply, error)
	// 抽奖 (聚合接口)
	// 对应: POST /api/v1/raffle/activity/draw
	Draw(context.Context, *DrawRequest) (*DrawReply, error)
	// 签到返利
	// 对应: POST /api/v1/raffle/activity/calendar_sign_rebate
	CalendarSignRebate(context.Context, *CalendarSignRebateRequest) (*CalendarSignRebateReply, error)
	// 判断是否签到
	// 对应: POST /api/v1/raffle/activity/is_calendar_sign_rebate
	IsCalendarSignRebate(context.Context, *IsCalendarSignRebateRequest) (*IsCalendarSignRebateReply, error)
	// 查询用户活动账户
	// 对应: POST /api/v1/raffle/activity/query_user_activity_account
	QueryUserActivityAccount(context.Context, *QueryUserActivityAccountRequest) (*QueryUserActivityAccountReply, error)
	mustEmbedUnimplementedActivityServer()
}

// UnimplementedActivityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivityServer struct{}

func (UnimplementedActivityServer) RaffleActivityArmory(context.Context, *RaffleActivityArmoryRequest) (*RaffleActivityArmoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RaffleActivityArmory not implemented")
}
func (UnimplementedActivityServer) Draw(context.Context, *DrawRequest) (*DrawReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Draw not implemented")
}
func (UnimplementedActivityServer) CalendarSignRebate(context.Context, *CalendarSignRebateRequest) (*CalendarSignRebateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CalendarSignRebate not implemented")
}
func (UnimplementedActivityServer) IsCalendarSignRebate(context.Context, *IsCalendarSignRebateRequest) (*IsCalendarSignRebateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method IsCalendarSignRebate not implemented")
}
func (UnimplementedActivityServer) QueryUserActivityAccount(context.Context, *QueryUserActivityAccountRequest) (*QueryUserActivityAccountReply, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryUserActivityAccount not implemented")
}
func (UnimplementedActivityServer) mustEmbedUnimplementedActivityServer() {}
func (UnimplementedActivityServer) testEmbeddedByValue()                  {}

// UnsafeActivityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityServer will
// result in compilation errors.
type UnsafeActivityServer interface {
	mustEmbedUnimplementedActivityServer()
}

func RegisterActivityServer(s grpc.ServiceRegistrar, srv ActivityServer) {
	// If the following call panics, it indicates UnimplementedActivityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Activity_ServiceDesc, srv)
}

func _Activity_RaffleActivityArmory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaffleActivityArmoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).RaffleActivityArmory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_RaffleActivityArmory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).RaffleActivityArmory(ctx, req.(*RaffleActivityArmoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_Draw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).Draw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_Draw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).Draw(ctx, req.(*DrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_CalendarSignRebate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalendarSignRebateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).CalendarSignRebate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_CalendarSignRebate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).CalendarSignRebate(ctx, req.(*CalendarSignRebateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_IsCalendarSignRebate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsCalendarSignRebateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).IsCalendarSignRebate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_IsCalendarSignRebate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).IsCalendarSignRebate(ctx, req.(*IsCalendarSignRebateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_QueryUserActivityAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserActivityAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).QueryUserActivityAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_QueryUserActivityAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).QueryUserActivityAccount(ctx, req.(*QueryUserActivityAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Activity_ServiceDesc is the grpc.ServiceDesc for Activity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Activity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.bigmarket.v1.Activity",
	HandlerType: (*ActivityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RaffleActivityArmory",
			Handler:    _Activity_RaffleActivityArmory_Handler,
		},
		{
			MethodName: "Draw",
			Handler:    _Activity_Draw_Handler,
		},
		{
			MethodName: "CalendarSignRebate",
			Handler:    _Activity_CalendarSignRebate_Handler,
		},
		{
			MethodName: "IsCalendarSignRebate",
			Handler:    _Activity_IsCalendarSignRebate_Handler,
		},
		{
			MethodName: "QueryUserActivityAccount",
			Handler:    _Activity_QueryUserActivityAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bigmarket/v1/activity.proto",
}
