// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: bigmarket/v1/strategy.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Strategy_StrategyArmory_FullMethodName                = "/api.bigmarket.v1.Strategy/StrategyArmory"
	Strategy_QueryRaffleAwardList_FullMethodName          = "/api.bigmarket.v1.Strategy/QueryRaffleAwardList"
	Strategy_RandomRaffle_FullMethodName                  = "/api.bigmarket.v1.Strategy/RandomRaffle"
	Strategy_QueryRaffleStrategyRuleWeight_FullMethodName = "/api.bigmarket.v1.Strategy/QueryRaffleStrategyRuleWeight"
)

// StrategyClient is the client API for Strategy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StrategyClient interface {
	// 装配抽奖策略
	// 对应: GET /api/v1/raffle/strategy/armory?strategy_id=xxx
	StrategyArmory(ctx context.Context, in *StrategyArmoryRequest, opts ...grpc.CallOption) (*StrategyArmoryReply, error)
	// 查询奖品列表
	// 对应: GET /api/v1/raffle/query_raffle_award_list?strategy_id=xxx
	QueryRaffleAwardList(ctx context.Context, in *QueryRaffleAwardListRequest, opts ...grpc.CallOption) (*QueryRaffleAwardListReply, error)
	// 随机抽奖接口 (核心计算)
	// 对应: GET /api/v1/raffle/random_raffle?strategy_id=xxx
	// 注意：虽然原接口是 GET，但为了传参规范，建议内部用 POST 或显式参数
	RandomRaffle(ctx context.Context, in *RandomRaffleRequest, opts ...grpc.CallOption) (*RandomRaffleReply, error)
	// 查询策略规则权重
	// 对应: POST /api/v1/raffle/strategy/query_raffle_strategy_rule_weight
	QueryRaffleStrategyRuleWeight(ctx context.Context, in *QueryRaffleStrategyRuleWeightRequest, opts ...grpc.CallOption) (*QueryRaffleStrategyRuleWeightReply, error)
}

type strategyClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategyClient(cc grpc.ClientConnInterface) StrategyClient {
	return &strategyClient{cc}
}

func (c *strategyClient) StrategyArmory(ctx context.Context, in *StrategyArmoryRequest, opts ...grpc.CallOption) (*StrategyArmoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyArmoryReply)
	err := c.cc.Invoke(ctx, Strategy_StrategyArmory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) QueryRaffleAwardList(ctx context.Context, in *QueryRaffleAwardListRequest, opts ...grpc.CallOption) (*QueryRaffleAwardListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRaffleAwardListReply)
	err := c.cc.Invoke(ctx, Strategy_QueryRaffleAwardList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) RandomRaffle(ctx context.Context, in *RandomRaffleRequest, opts ...grpc.CallOption) (*RandomRaffleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RandomRaffleReply)
	err := c.cc.Invoke(ctx, Strategy_RandomRaffle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) QueryRaffleStrategyRuleWeight(ctx context.Context, in *QueryRaffleStrategyRuleWeightRequest, opts ...grpc.CallOption) (*QueryRaffleStrategyRuleWeightReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRaffleStrategyRuleWeightReply)
	err := c.cc.Invoke(ctx, Strategy_QueryRaffleStrategyRuleWeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyServer is the server API for Strategy service.
// All implementations must embed UnimplementedStrategyServer
// for forward compatibility.
type StrategyServer interface {
	// 装配抽奖策略
	// 对应: GET /api/v1/raffle/strategy/armory?strategy_id=xxx
	StrategyArmory(context.Context, *StrategyArmoryRequest) (*StrategyArmoryReply, error)
	// 查询奖品列表
	// 对应: GET /api/v1/raffle/query_raffle_award_list?strategy_id=xxx
	QueryRaffleAwardList(context.Context, *QueryRaffleAwardListRequest) (*QueryRaffleAwardListReply, error)
	// 随机抽奖接口 (核心计算)
	// 对应: GET /api/v1/raffle/random_raffle?strategy_id=xxx
	// 注意：虽然原接口是 GET，但为了传参规范，建议内部用 POST 或显式参数
	RandomRaffle(context.Context, *RandomRaffleRequest) (*RandomRaffleReply, error)
	// 查询策略规则权重
	// 对应: POST /api/v1/raffle/strategy/query_raffle_strategy_rule_weight
	QueryRaffleStrategyRuleWeight(context.Context, *QueryRaffleStrategyRuleWeightRequest) (*QueryRaffleStrategyRuleWeightReply, error)
	mustEmbedUnimplementedStrategyServer()
}

// UnimplementedStrategyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStrategyServer struct{}

func (UnimplementedStrategyServer) StrategyArmory(context.Context, *StrategyArmoryRequest) (*StrategyArmoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StrategyArmory not implemented")
}
func (UnimplementedStrategyServer) QueryRaffleAwardList(context.Context, *QueryRaffleAwardListRequest) (*QueryRaffleAwardListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryRaffleAwardList not implemented")
}
func (UnimplementedStrategyServer) RandomRaffle(context.Context, *RandomRaffleRequest) (*RandomRaffleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RandomRaffle not implemented")
}
func (UnimplementedStrategyServer) QueryRaffleStrategyRuleWeight(context.Context, *QueryRaffleStrategyRuleWeightRequest) (*QueryRaffleStrategyRuleWeightReply, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryRaffleStrategyRuleWeight not implemented")
}
func (UnimplementedStrategyServer) mustEmbedUnimplementedStrategyServer() {}
func (UnimplementedStrategyServer) testEmbeddedByValue()                  {}

// UnsafeStrategyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrategyServer will
// result in compilation errors.
type UnsafeStrategyServer interface {
	mustEmbedUnimplementedStrategyServer()
}

func RegisterStrategyServer(s grpc.ServiceRegistrar, srv StrategyServer) {
	// If the following call panics, it indicates UnimplementedStrategyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Strategy_ServiceDesc, srv)
}

func _Strategy_StrategyArmory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyArmoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).StrategyArmory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_StrategyArmory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).StrategyArmory(ctx, req.(*StrategyArmoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_QueryRaffleAwardList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRaffleAwardListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).QueryRaffleAwardList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_QueryRaffleAwardList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).QueryRaffleAwardList(ctx, req.(*QueryRaffleAwardListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_RandomRaffle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomRaffleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).RandomRaffle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_RandomRaffle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).RandomRaffle(ctx, req.(*RandomRaffleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_QueryRaffleStrategyRuleWeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRaffleStrategyRuleWeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).QueryRaffleStrategyRuleWeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_QueryRaffleStrategyRuleWeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).QueryRaffleStrategyRuleWeight(ctx, req.(*QueryRaffleStrategyRuleWeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Strategy_ServiceDesc is the grpc.ServiceDesc for Strategy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Strategy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.bigmarket.v1.Strategy",
	HandlerType: (*StrategyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StrategyArmory",
			Handler:    _Strategy_StrategyArmory_Handler,
		},
		{
			MethodName: "QueryRaffleAwardList",
			Handler:    _Strategy_QueryRaffleAwardList_Handler,
		},
		{
			MethodName: "RandomRaffle",
			Handler:    _Strategy_RandomRaffle_Handler,
		},
		{
			MethodName: "QueryRaffleStrategyRuleWeight",
			Handler:    _Strategy_QueryRaffleStrategyRuleWeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bigmarket/v1/strategy.proto",
}
