// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.4
// source: bigmarket/v1/strategy.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationStrategyQueryRaffleAwardList = "/api.bigmarket.v1.Strategy/QueryRaffleAwardList"
const OperationStrategyQueryRaffleStrategyRuleWeight = "/api.bigmarket.v1.Strategy/QueryRaffleStrategyRuleWeight"
const OperationStrategyRandomRaffle = "/api.bigmarket.v1.Strategy/RandomRaffle"
const OperationStrategyStrategyArmory = "/api.bigmarket.v1.Strategy/StrategyArmory"

type StrategyHTTPServer interface {
	// QueryRaffleAwardList 查询奖品列表
	// 对应: GET /api/v1/raffle/query_raffle_award_list?strategy_id=xxx
	QueryRaffleAwardList(context.Context, *QueryRaffleAwardListRequest) (*QueryRaffleAwardListReply, error)
	// QueryRaffleStrategyRuleWeight 查询策略规则权重
	// 对应: POST /api/v1/raffle/strategy/query_raffle_strategy_rule_weight
	QueryRaffleStrategyRuleWeight(context.Context, *QueryRaffleStrategyRuleWeightRequest) (*QueryRaffleStrategyRuleWeightReply, error)
	// RandomRaffle 随机抽奖接口 (核心计算)
	// 对应: GET /api/v1/raffle/random_raffle?strategy_id=xxx
	// 注意：虽然原接口是 GET，但为了传参规范，建议内部用 POST 或显式参数
	RandomRaffle(context.Context, *RandomRaffleRequest) (*RandomRaffleReply, error)
	// StrategyArmory 装配抽奖策略
	// 对应: GET /api/v1/raffle/strategy/armory?strategy_id=xxx
	StrategyArmory(context.Context, *StrategyArmoryRequest) (*StrategyArmoryReply, error)
}

func RegisterStrategyHTTPServer(s *http.Server, srv StrategyHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/strategy/raffle/strategy/armory", _Strategy_StrategyArmory0_HTTP_Handler(srv))
	r.GET("/api/v1/strategy/raffle/strategy/query_raffle_award_list", _Strategy_QueryRaffleAwardList0_HTTP_Handler(srv))
	r.POST("/api/v1/strategy/raffle/strategy/random_raffle", _Strategy_RandomRaffle0_HTTP_Handler(srv))
	r.POST("/api/v1/strategy/raffle/strategy/query_raffle_strategy_rule_weight", _Strategy_QueryRaffleStrategyRuleWeight0_HTTP_Handler(srv))
}

func _Strategy_StrategyArmory0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StrategyArmoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyStrategyArmory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StrategyArmory(ctx, req.(*StrategyArmoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StrategyArmoryReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_QueryRaffleAwardList0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in QueryRaffleAwardListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyQueryRaffleAwardList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueryRaffleAwardList(ctx, req.(*QueryRaffleAwardListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueryRaffleAwardListReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_RandomRaffle0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RandomRaffleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyRandomRaffle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RandomRaffle(ctx, req.(*RandomRaffleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RandomRaffleReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_QueryRaffleStrategyRuleWeight0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in QueryRaffleStrategyRuleWeightRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyQueryRaffleStrategyRuleWeight)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueryRaffleStrategyRuleWeight(ctx, req.(*QueryRaffleStrategyRuleWeightRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueryRaffleStrategyRuleWeightReply)
		return ctx.Result(200, reply)
	}
}

type StrategyHTTPClient interface {
	// QueryRaffleAwardList 查询奖品列表
	// 对应: GET /api/v1/raffle/query_raffle_award_list?strategy_id=xxx
	QueryRaffleAwardList(ctx context.Context, req *QueryRaffleAwardListRequest, opts ...http.CallOption) (rsp *QueryRaffleAwardListReply, err error)
	// QueryRaffleStrategyRuleWeight 查询策略规则权重
	// 对应: POST /api/v1/raffle/strategy/query_raffle_strategy_rule_weight
	QueryRaffleStrategyRuleWeight(ctx context.Context, req *QueryRaffleStrategyRuleWeightRequest, opts ...http.CallOption) (rsp *QueryRaffleStrategyRuleWeightReply, err error)
	// RandomRaffle 随机抽奖接口 (核心计算)
	// 对应: GET /api/v1/raffle/random_raffle?strategy_id=xxx
	// 注意：虽然原接口是 GET，但为了传参规范，建议内部用 POST 或显式参数
	RandomRaffle(ctx context.Context, req *RandomRaffleRequest, opts ...http.CallOption) (rsp *RandomRaffleReply, err error)
	// StrategyArmory 装配抽奖策略
	// 对应: GET /api/v1/raffle/strategy/armory?strategy_id=xxx
	StrategyArmory(ctx context.Context, req *StrategyArmoryRequest, opts ...http.CallOption) (rsp *StrategyArmoryReply, err error)
}

type StrategyHTTPClientImpl struct {
	cc *http.Client
}

func NewStrategyHTTPClient(client *http.Client) StrategyHTTPClient {
	return &StrategyHTTPClientImpl{client}
}

// QueryRaffleAwardList 查询奖品列表
// 对应: GET /api/v1/raffle/query_raffle_award_list?strategy_id=xxx
func (c *StrategyHTTPClientImpl) QueryRaffleAwardList(ctx context.Context, in *QueryRaffleAwardListRequest, opts ...http.CallOption) (*QueryRaffleAwardListReply, error) {
	var out QueryRaffleAwardListReply
	pattern := "/api/v1/strategy/raffle/strategy/query_raffle_award_list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyQueryRaffleAwardList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// QueryRaffleStrategyRuleWeight 查询策略规则权重
// 对应: POST /api/v1/raffle/strategy/query_raffle_strategy_rule_weight
func (c *StrategyHTTPClientImpl) QueryRaffleStrategyRuleWeight(ctx context.Context, in *QueryRaffleStrategyRuleWeightRequest, opts ...http.CallOption) (*QueryRaffleStrategyRuleWeightReply, error) {
	var out QueryRaffleStrategyRuleWeightReply
	pattern := "/api/v1/strategy/raffle/strategy/query_raffle_strategy_rule_weight"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyQueryRaffleStrategyRuleWeight))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RandomRaffle 随机抽奖接口 (核心计算)
// 对应: GET /api/v1/raffle/random_raffle?strategy_id=xxx
// 注意：虽然原接口是 GET，但为了传参规范，建议内部用 POST 或显式参数
func (c *StrategyHTTPClientImpl) RandomRaffle(ctx context.Context, in *RandomRaffleRequest, opts ...http.CallOption) (*RandomRaffleReply, error) {
	var out RandomRaffleReply
	pattern := "/api/v1/strategy/raffle/strategy/random_raffle"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyRandomRaffle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StrategyArmory 装配抽奖策略
// 对应: GET /api/v1/raffle/strategy/armory?strategy_id=xxx
func (c *StrategyHTTPClientImpl) StrategyArmory(ctx context.Context, in *StrategyArmoryRequest, opts ...http.CallOption) (*StrategyArmoryReply, error) {
	var out StrategyArmoryReply
	pattern := "/api/v1/strategy/raffle/strategy/armory"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyStrategyArmory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
