// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: bigmarket/v1/strategy.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StrategyArmoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"` // 修正: 装配的是策略，不是活动
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyArmoryRequest) Reset() {
	*x = StrategyArmoryRequest{}
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyArmoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyArmoryRequest) ProtoMessage() {}

func (x *StrategyArmoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyArmoryRequest.ProtoReflect.Descriptor instead.
func (*StrategyArmoryRequest) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *StrategyArmoryRequest) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

type StrategyArmoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyArmoryReply) Reset() {
	*x = StrategyArmoryReply{}
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyArmoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyArmoryReply) ProtoMessage() {}

func (x *StrategyArmoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyArmoryReply.ProtoReflect.Descriptor instead.
func (*StrategyArmoryReply) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *StrategyArmoryReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type QueryRaffleAwardListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"` // 修正: 查的是策略下的奖品
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              // 可选: 用于后续扩展（如根据用户过滤）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRaffleAwardListRequest) Reset() {
	*x = QueryRaffleAwardListRequest{}
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRaffleAwardListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRaffleAwardListRequest) ProtoMessage() {}

func (x *QueryRaffleAwardListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRaffleAwardListRequest.ProtoReflect.Descriptor instead.
func (*QueryRaffleAwardListRequest) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRaffleAwardListRequest) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

func (x *QueryRaffleAwardListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RaffleAward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AwardId       int64                  `protobuf:"varint,1,opt,name=award_id,json=awardId,proto3" json:"award_id,omitempty"`
	AwardTitle    string                 `protobuf:"bytes,2,opt,name=award_title,json=awardTitle,proto3" json:"award_title,omitempty"`
	AwardSubtitle string                 `protobuf:"bytes,3,opt,name=award_subtitle,json=awardSubtitle,proto3" json:"award_subtitle,omitempty"`
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaffleAward) Reset() {
	*x = RaffleAward{}
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaffleAward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaffleAward) ProtoMessage() {}

func (x *RaffleAward) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaffleAward.ProtoReflect.Descriptor instead.
func (*RaffleAward) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *RaffleAward) GetAwardId() int64 {
	if x != nil {
		return x.AwardId
	}
	return 0
}

func (x *RaffleAward) GetAwardTitle() string {
	if x != nil {
		return x.AwardTitle
	}
	return ""
}

func (x *RaffleAward) GetAwardSubtitle() string {
	if x != nil {
		return x.AwardSubtitle
	}
	return ""
}

func (x *RaffleAward) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type QueryRaffleAwardListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Awards        []*RaffleAward         `protobuf:"bytes,1,rep,name=awards,proto3" json:"awards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRaffleAwardListReply) Reset() {
	*x = QueryRaffleAwardListReply{}
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRaffleAwardListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRaffleAwardListReply) ProtoMessage() {}

func (x *QueryRaffleAwardListReply) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRaffleAwardListReply.ProtoReflect.Descriptor instead.
func (*QueryRaffleAwardListReply) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_strategy_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRaffleAwardListReply) GetAwards() []*RaffleAward {
	if x != nil {
		return x.Awards
	}
	return nil
}

type RandomRaffleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 补充: 抽奖必须知道是谁
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomRaffleRequest) Reset() {
	*x = RandomRaffleRequest{}
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomRaffleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomRaffleRequest) ProtoMessage() {}

func (x *RandomRaffleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomRaffleRequest.ProtoReflect.Descriptor instead.
func (*RandomRaffleRequest) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_strategy_proto_rawDescGZIP(), []int{5}
}

func (x *RandomRaffleRequest) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

func (x *RandomRaffleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RandomRaffleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AwardId       int64                  `protobuf:"varint,1,opt,name=award_id,json=awardId,proto3" json:"award_id,omitempty"`
	AwardTitle    string                 `protobuf:"bytes,2,opt,name=award_title,json=awardTitle,proto3" json:"award_title,omitempty"`
	AwardIndex    int32                  `protobuf:"varint,3,opt,name=award_index,json=awardIndex,proto3" json:"award_index,omitempty"` // 补充: 奖品顺序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomRaffleReply) Reset() {
	*x = RandomRaffleReply{}
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomRaffleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomRaffleReply) ProtoMessage() {}

func (x *RandomRaffleReply) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomRaffleReply.ProtoReflect.Descriptor instead.
func (*RandomRaffleReply) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_strategy_proto_rawDescGZIP(), []int{6}
}

func (x *RandomRaffleReply) GetAwardId() int64 {
	if x != nil {
		return x.AwardId
	}
	return 0
}

func (x *RandomRaffleReply) GetAwardTitle() string {
	if x != nil {
		return x.AwardTitle
	}
	return ""
}

func (x *RandomRaffleReply) GetAwardIndex() int32 {
	if x != nil {
		return x.AwardIndex
	}
	return 0
}

type QueryRaffleStrategyRuleWeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRaffleStrategyRuleWeightRequest) Reset() {
	*x = QueryRaffleStrategyRuleWeightRequest{}
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRaffleStrategyRuleWeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRaffleStrategyRuleWeightRequest) ProtoMessage() {}

func (x *QueryRaffleStrategyRuleWeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRaffleStrategyRuleWeightRequest.ProtoReflect.Descriptor instead.
func (*QueryRaffleStrategyRuleWeightRequest) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_strategy_proto_rawDescGZIP(), []int{7}
}

func (x *QueryRaffleStrategyRuleWeightRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryRaffleStrategyRuleWeightRequest) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type StrategyAward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AwardId       int64                  `protobuf:"varint,1,opt,name=award_id,json=awardId,proto3" json:"award_id,omitempty"`
	AwardTitle    string                 `protobuf:"bytes,2,opt,name=award_title,json=awardTitle,proto3" json:"award_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyAward) Reset() {
	*x = StrategyAward{}
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyAward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyAward) ProtoMessage() {}

func (x *StrategyAward) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyAward.ProtoReflect.Descriptor instead.
func (*StrategyAward) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_strategy_proto_rawDescGZIP(), []int{8}
}

func (x *StrategyAward) GetAwardId() int64 {
	if x != nil {
		return x.AwardId
	}
	return 0
}

func (x *StrategyAward) GetAwardTitle() string {
	if x != nil {
		return x.AwardTitle
	}
	return ""
}

type RuleWeightResponse struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	RuleWeightCount                  int64                  `protobuf:"varint,1,opt,name=rule_weight_count,json=ruleWeightCount,proto3" json:"rule_weight_count,omitempty"`
	UserActivityAccountTotalUseCount int64                  `protobuf:"varint,2,opt,name=user_activity_account_total_use_count,json=userActivityAccountTotalUseCount,proto3" json:"user_activity_account_total_use_count,omitempty"`
	StrategyAwards                   []*StrategyAward       `protobuf:"bytes,3,rep,name=strategy_awards,json=strategyAwards,proto3" json:"strategy_awards,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *RuleWeightResponse) Reset() {
	*x = RuleWeightResponse{}
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleWeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleWeightResponse) ProtoMessage() {}

func (x *RuleWeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleWeightResponse.ProtoReflect.Descriptor instead.
func (*RuleWeightResponse) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_strategy_proto_rawDescGZIP(), []int{9}
}

func (x *RuleWeightResponse) GetRuleWeightCount() int64 {
	if x != nil {
		return x.RuleWeightCount
	}
	return 0
}

func (x *RuleWeightResponse) GetUserActivityAccountTotalUseCount() int64 {
	if x != nil {
		return x.UserActivityAccountTotalUseCount
	}
	return 0
}

func (x *RuleWeightResponse) GetStrategyAwards() []*StrategyAward {
	if x != nil {
		return x.StrategyAwards
	}
	return nil
}

type QueryRaffleStrategyRuleWeightReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RuleWeightList []*RuleWeightResponse  `protobuf:"bytes,1,rep,name=rule_weight_list,json=ruleWeightList,proto3" json:"rule_weight_list,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryRaffleStrategyRuleWeightReply) Reset() {
	*x = QueryRaffleStrategyRuleWeightReply{}
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRaffleStrategyRuleWeightReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRaffleStrategyRuleWeightReply) ProtoMessage() {}

func (x *QueryRaffleStrategyRuleWeightReply) ProtoReflect() protoreflect.Message {
	mi := &file_bigmarket_v1_strategy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRaffleStrategyRuleWeightReply.ProtoReflect.Descriptor instead.
func (*QueryRaffleStrategyRuleWeightReply) Descriptor() ([]byte, []int) {
	return file_bigmarket_v1_strategy_proto_rawDescGZIP(), []int{10}
}

func (x *QueryRaffleStrategyRuleWeightReply) GetRuleWeightList() []*RuleWeightResponse {
	if x != nil {
		return x.RuleWeightList
	}
	return nil
}

var File_bigmarket_v1_strategy_proto protoreflect.FileDescriptor

const file_bigmarket_v1_strategy_proto_rawDesc = "" +
	"\n" +
	"\x1bbigmarket/v1/strategy.proto\x12\x10api.bigmarket.v1\x1a\x1cgoogle/api/annotations.proto\"8\n" +
	"\x15StrategyArmoryRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\"/\n" +
	"\x13StrategyArmoryReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"W\n" +
	"\x1bQueryRaffleAwardListRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x84\x01\n" +
	"\vRaffleAward\x12\x19\n" +
	"\baward_id\x18\x01 \x01(\x03R\aawardId\x12\x1f\n" +
	"\vaward_title\x18\x02 \x01(\tR\n" +
	"awardTitle\x12%\n" +
	"\x0eaward_subtitle\x18\x03 \x01(\tR\rawardSubtitle\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\"R\n" +
	"\x19QueryRaffleAwardListReply\x125\n" +
	"\x06awards\x18\x01 \x03(\v2\x1d.api.bigmarket.v1.RaffleAwardR\x06awards\"O\n" +
	"\x13RandomRaffleRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"p\n" +
	"\x11RandomRaffleReply\x12\x19\n" +
	"\baward_id\x18\x01 \x01(\x03R\aawardId\x12\x1f\n" +
	"\vaward_title\x18\x02 \x01(\tR\n" +
	"awardTitle\x12\x1f\n" +
	"\vaward_index\x18\x03 \x01(\x05R\n" +
	"awardIndex\"`\n" +
	"$QueryRaffleStrategyRuleWeightRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\"K\n" +
	"\rStrategyAward\x12\x19\n" +
	"\baward_id\x18\x01 \x01(\x03R\aawardId\x12\x1f\n" +
	"\vaward_title\x18\x02 \x01(\tR\n" +
	"awardTitle\"\xdb\x01\n" +
	"\x12RuleWeightResponse\x12*\n" +
	"\x11rule_weight_count\x18\x01 \x01(\x03R\x0fruleWeightCount\x12O\n" +
	"%user_activity_account_total_use_count\x18\x02 \x01(\x03R userActivityAccountTotalUseCount\x12H\n" +
	"\x0fstrategy_awards\x18\x03 \x03(\v2\x1f.api.bigmarket.v1.StrategyAwardR\x0estrategyAwards\"t\n" +
	"\"QueryRaffleStrategyRuleWeightReply\x12N\n" +
	"\x10rule_weight_list\x18\x01 \x03(\v2$.api.bigmarket.v1.RuleWeightResponseR\x0eruleWeightList2\xcc\x05\n" +
	"\bStrategy\x12\x91\x01\n" +
	"\x0eStrategyArmory\x12'.api.bigmarket.v1.StrategyArmoryRequest\x1a%.api.bigmarket.v1.StrategyArmoryReply\"/\x82\xd3\xe4\x93\x02)\x12'/api/v1/strategy/raffle/strategy/armory\x12\xb4\x01\n" +
	"\x14QueryRaffleAwardList\x12-.api.bigmarket.v1.QueryRaffleAwardListRequest\x1a+.api.bigmarket.v1.QueryRaffleAwardListReply\"@\x82\xd3\xe4\x93\x02:\x128/api/v1/strategy/raffle/strategy/query_raffle_award_list\x12\x95\x01\n" +
	"\fRandomRaffle\x12%.api.bigmarket.v1.RandomRaffleRequest\x1a#.api.bigmarket.v1.RandomRaffleReply\"9\x82\xd3\xe4\x93\x023:\x01*\"./api/v1/strategy/raffle/strategy/random_raffle\x12\xdc\x01\n" +
	"\x1dQueryRaffleStrategyRuleWeight\x126.api.bigmarket.v1.QueryRaffleStrategyRuleWeightRequest\x1a4.api.bigmarket.v1.QueryRaffleStrategyRuleWeightReply\"M\x82\xd3\xe4\x93\x02G:\x01*\"B/api/v1/strategy/raffle/strategy/query_raffle_strategy_rule_weightB;\n" +
	"\x10api.bigmarket.v1P\x01Z%big-market-kratos/api/bigmarket/v1;v1b\x06proto3"

var (
	file_bigmarket_v1_strategy_proto_rawDescOnce sync.Once
	file_bigmarket_v1_strategy_proto_rawDescData []byte
)

func file_bigmarket_v1_strategy_proto_rawDescGZIP() []byte {
	file_bigmarket_v1_strategy_proto_rawDescOnce.Do(func() {
		file_bigmarket_v1_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bigmarket_v1_strategy_proto_rawDesc), len(file_bigmarket_v1_strategy_proto_rawDesc)))
	})
	return file_bigmarket_v1_strategy_proto_rawDescData
}

var file_bigmarket_v1_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_bigmarket_v1_strategy_proto_goTypes = []any{
	(*StrategyArmoryRequest)(nil),                // 0: api.bigmarket.v1.StrategyArmoryRequest
	(*StrategyArmoryReply)(nil),                  // 1: api.bigmarket.v1.StrategyArmoryReply
	(*QueryRaffleAwardListRequest)(nil),          // 2: api.bigmarket.v1.QueryRaffleAwardListRequest
	(*RaffleAward)(nil),                          // 3: api.bigmarket.v1.RaffleAward
	(*QueryRaffleAwardListReply)(nil),            // 4: api.bigmarket.v1.QueryRaffleAwardListReply
	(*RandomRaffleRequest)(nil),                  // 5: api.bigmarket.v1.RandomRaffleRequest
	(*RandomRaffleReply)(nil),                    // 6: api.bigmarket.v1.RandomRaffleReply
	(*QueryRaffleStrategyRuleWeightRequest)(nil), // 7: api.bigmarket.v1.QueryRaffleStrategyRuleWeightRequest
	(*StrategyAward)(nil),                        // 8: api.bigmarket.v1.StrategyAward
	(*RuleWeightResponse)(nil),                   // 9: api.bigmarket.v1.RuleWeightResponse
	(*QueryRaffleStrategyRuleWeightReply)(nil),   // 10: api.bigmarket.v1.QueryRaffleStrategyRuleWeightReply
}
var file_bigmarket_v1_strategy_proto_depIdxs = []int32{
	3,  // 0: api.bigmarket.v1.QueryRaffleAwardListReply.awards:type_name -> api.bigmarket.v1.RaffleAward
	8,  // 1: api.bigmarket.v1.RuleWeightResponse.strategy_awards:type_name -> api.bigmarket.v1.StrategyAward
	9,  // 2: api.bigmarket.v1.QueryRaffleStrategyRuleWeightReply.rule_weight_list:type_name -> api.bigmarket.v1.RuleWeightResponse
	0,  // 3: api.bigmarket.v1.Strategy.StrategyArmory:input_type -> api.bigmarket.v1.StrategyArmoryRequest
	2,  // 4: api.bigmarket.v1.Strategy.QueryRaffleAwardList:input_type -> api.bigmarket.v1.QueryRaffleAwardListRequest
	5,  // 5: api.bigmarket.v1.Strategy.RandomRaffle:input_type -> api.bigmarket.v1.RandomRaffleRequest
	7,  // 6: api.bigmarket.v1.Strategy.QueryRaffleStrategyRuleWeight:input_type -> api.bigmarket.v1.QueryRaffleStrategyRuleWeightRequest
	1,  // 7: api.bigmarket.v1.Strategy.StrategyArmory:output_type -> api.bigmarket.v1.StrategyArmoryReply
	4,  // 8: api.bigmarket.v1.Strategy.QueryRaffleAwardList:output_type -> api.bigmarket.v1.QueryRaffleAwardListReply
	6,  // 9: api.bigmarket.v1.Strategy.RandomRaffle:output_type -> api.bigmarket.v1.RandomRaffleReply
	10, // 10: api.bigmarket.v1.Strategy.QueryRaffleStrategyRuleWeight:output_type -> api.bigmarket.v1.QueryRaffleStrategyRuleWeightReply
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_bigmarket_v1_strategy_proto_init() }
func file_bigmarket_v1_strategy_proto_init() {
	if File_bigmarket_v1_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bigmarket_v1_strategy_proto_rawDesc), len(file_bigmarket_v1_strategy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bigmarket_v1_strategy_proto_goTypes,
		DependencyIndexes: file_bigmarket_v1_strategy_proto_depIdxs,
		MessageInfos:      file_bigmarket_v1_strategy_proto_msgTypes,
	}.Build()
	File_bigmarket_v1_strategy_proto = out.File
	file_bigmarket_v1_strategy_proto_goTypes = nil
	file_bigmarket_v1_strategy_proto_depIdxs = nil
}
